###
###   Docker file for the ucis4eq services
###
version: '3'

services:
  # UCIS4EQ Slip Generator service  
  slipgen:
    build: 
      context: .
      dockerfile: deployment/dockers/Dockerfile-credentials
      args:
        SSH_PRV: $SSH_PRV   
        PD_USER: $PD_USER   
        IMAGE: registry.gitlab.com/cheese-coe/ucis4eq/slipgen
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1        
    volumes:
      - ./data/DAL.json:/opt/DAL.json
      - ./data/Sites.json:/opt/Sites.json
      - ./code/services/slipGenService.py:/opt/services/slipGenService.py
      - ./code/components/:/usr/local/lib/python3.7/dist-packages/ucis4eq
    #entrypoint: ["/bin/bash", "/opt/services/start.sh"]

  # UCIS4EQ Salvus
  salvus:
    build: 
      context: .
      dockerfile: deployment/dockers/Dockerfile-credentials
      args:
        SSH_PRV: $SSH_PRV   
        PD_USER: $PD_USER   
        IMAGE: registry.gitlab.com/cheese-coe/ucis4eq/salvus    
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1    
    volumes:
      - ./data/DAL.json:/opt/DAL.json
      - ./data/Sites.json:/opt/Sites.json      
      - ./code/services/salvusService.py:/opt/services/salvusService.py
      - ./code/components/:/usr/local/lib/python3.8/site-packages/ucis4eq
    #entrypoint: ["/bin/bash", "/opt/services/start.sh"]
      
  # UCIS4EQ Micro-services 
  microservices:
    build: 
      context: .
      dockerfile: deployment/dockers/Dockerfile-credentials
      args:
        SSH_PRV: $SSH_PRV   
        PD_USER: $PD_USER   
        IMAGE: registry.gitlab.com/cheese-coe/ucis4eq/microservices    
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1    
    volumes:
      - ./data/DAL.json:/opt/DAL.json
      - ./data/Sites.json:/opt/Sites.json      
      - ./code/components/:/usr/local/lib/python3.8/site-packages/ucis4eq
      - ./code/services/microServices.py:/root/services/microServices.py
    depends_on:
      - DAL
  
  # UCIS4EQ Workflow Manager service  
  workflowmanager:
    image: registry.gitlab.com/cheese-coe/ucis4eq/workflowmanager
    network_mode: "host"
    environment:
      - UCIS4EQ_LOCATION=${LOCATION}
      - PYTHONUNBUFFERED=1
      - COMPSS_HTTP_POOL_SIZE=100
    volumes:
      - ./data/project.xml:/opt/project.xml
      - ./data/resources.xml:/opt/resources.xml          
      - ./code/components/:/usr/local/lib/python3.8/site-packages/ucis4eq
      - ./code/services/workflowManagerService.py:/root/services/workflowManagerService.py      
      - ./data/resources.xml:/usr/local/lib/python3.8/site-packages/pycompss/COMPSs/Runtime/configuration/xml/resources/default_resources.xml
      - ./data/project.xml:/usr/local/lib/python3.8/site-packages/pycompss/COMPSs/Runtime/configuration/xml/projects/default_project.xml
      - ./results/pycompss:/root/.COMPSs/
        
  # Mongo DataBase 
  DAL:
    image: mongo:4.2
    command: mongod --quiet --logpath /dev/null    
    ports:
      - "27017:27017"
    restart: always
    
  # UCIS4EQ Listener service
  listener:
    image: registry.gitlab.com/cheese-coe/ucis4eq/listener
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1        
    volumes:
      - ./data/DAL.json:/opt/DAL.json
      - ./data/Sites.json:/opt/Sites.json      
      - ./code/components/:/usr/local/lib/python3.5/site-packages/ucis4eq
      - ./code/services/listener.py:/root/services/listener.py
    restart: always      
    depends_on:
      - DAL
      - workflowmanager
      - microservices
      
  # UCIS4EQ Dashboard service
  dashboard:
    container_name: ucis4eq_dashboard     
    build: 
      context: .      
      dockerfile: deployment/dockers/Dockerfile-credentials
      args:
        SSH_PRV: $SSH_PRV   
        PD_USER: $PD_USER   
        IMAGE: registry.gitlab.com/cheese-coe/ucis4eq/dashboard
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1        
    volumes:
      - ./data/DAL.json:/opt/DAL.json      
      - ./code/components/:/usr/local/lib/python3.7/site-packages/ucis4eq
      - ./code/services/dashboard.py:/root/services/dashboard.py
      - ./deployment/dockers/dashboard/assets:/root/services/assets
