###
###   Docker file for the ucis4eq services
###
version: '3'

services:
  # UCIS4EQ Slip Generator service  
  slipGen:
    image: registry.gitlab.com/cheese-coe/ucis4eq/slipgen
    network_mode: "host"
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json   
      - ${UCIS4EQ_HOME}/code/services/slipGenService.py:/root/services/slipGenService.py
      - ${UCIS4EQ_HOME}/code/components/:/usr/local/lib/python3.7/dist-packages/ucis4eq

    entrypoint: ["/bin/bash", "/root/services/start.sh"]
    #restart: always

  # UCIS4EQ Salvus
  salvus:
    image: registry.gitlab.com/cheese-coe/ucis4eq/salvus
    network_mode: "host"
    environment:
      SALVUS_USERNAME: ${SALVUS_USERNAME}
      SALVUS_PASSWORD: ${SALVUS_PASSWORD}
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json
      - ${UCIS4EQ_HOME}/code/services/salvusService.py:/root/services/salvusService.py
      - ${UCIS4EQ_HOME}/code/components/:/root/miniconda3/envs/salvus/lib/python3.7/site-packages/ucis4eq
    entrypoint: ["/bin/bash", "/root/services/start.sh"]
    
    #restart: always
  
  # UCIS4EQ Micro-services 
  microServices:
    image: registry.gitlab.com/cheese-coe/ucis4eq/microservices
    network_mode: "host"
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json
      - ${UCIS4EQ_HOME}/code/components/:/usr/local/lib/python3.7/site-packages/ucis4eq
      - ${UCIS4EQ_HOME}/code/services/microServices.py:/root/services/microServices.py
    depends_on:
      - DAL
    #restart: always  
  
  # UCIS4EQ Workflow Manager service  
  workflowManager:
    image: registry.gitlab.com/cheese-coe/ucis4eq/workflowmanager
    network_mode: "host"
    depends_on:
      - slipGen
      - microServices
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json   
      - ${UCIS4EQ_HOME}/code/components/:/usr/local/lib/python3.7/site-packages/ucis4eq
      - ${UCIS4EQ_HOME}/code/services/workflowManagerService.py:/root/services/workflowManagerService.py

    #restart: always

  # Mongo DataBase 
  DAL:
    network_mode: "host"
    image: mongo:4.2
    ports:
      - "27017:27017"
    restart: always
    
  # UCIS4EQ Listener service
  listener:
    image: registry.gitlab.com/cheese-coe/ucis4eq/listener
    network_mode: "host"
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json
      - ${UCIS4EQ_HOME}/code/components/:/usr/local/lib/python3.5/site-packages/ucis4eq
      - ${UCIS4EQ_HOME}/code/services/listener.py:/root/services/listener.py

    #restart: always
    depends_on:
      - DAL
      - workflowManager
      - microServices
