###
###   Docker file for the ucis4eq services
###
version: '3'

services:
  # UCIS4EQ Slip Generator service  
  slipGen:
    image: registry.gitlab.com/cheese-coe/ucis4eq/slipgen
    network_mode: "host"
    volumes:
      - ${UCIS4EQ_DAL}:/opt/DAL.json   

    entrypoint: ["/bin/bash", "/opt/services/start.sh"]
    depends_on:
      - DAL    

  # UCIS4EQ Salvus
  salvus:
    image: registry.gitlab.com/cheese-coe/ucis4eq/salvus
    network_mode: "host"
    volumes:
      - ~/.ssh:/root/.ssh
      - ${UCIS4EQ_ENV}:/root/env.source
      - ${UCIS4EQ_DAL}:/root/DAL.json
    entrypoint: ["/bin/bash", "/root/services/start.sh"]
    depends_on:
      - DAL    
      
  # UCIS4EQ Micro-services 
  microServices:
    image: registry.gitlab.com/cheese-coe/ucis4eq/microservices
    network_mode: "host"
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json
    depends_on:
      - DAL
  
  # UCIS4EQ Workflow Manager service  
  workflowManager:
    image: registry.gitlab.com/cheese-coe/ucis4eq/workflowmanager
    network_mode: "host"
    depends_on:
      - microServices
      - slipGen
      - salvus      
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json   
    depends_on:
      - DAL

  # Mongo DataBase 
  DAL:
    network_mode: "host"
    image: mongo:4.2
    ports:
      - "27017:27017"
    restart: always
    
  # UCIS4EQ Listener service
  listener:
    image: registry.gitlab.com/cheese-coe/ucis4eq/listener
    network_mode: "host"
    volumes:
      - ${UCIS4EQ_DAL}:/root/DAL.json

    #restart: always
    depends_on:
      - DAL
      - workflowManager
      - microServices
