close all
clear

% edges={'Tini', 'Tini', 'Tini', ... 
%        'UCp1', 'UCp1', 'UCp1', 'UCp1', ...
%        'UCp2','UCp2', 'UCp2', ...
%        'BG1', 'BG2', 'BG3', 'BG4', ...
%        'Comp1', 'Comp2', 'Comp2', 'Comp2', ...
%        'Comp3.1', 'Comp3.2', 'Comp3.n', ...
%        'Comp4.1', 'Comp4.2', 'Comp4.n', ...
%        'Comp4.1', 'Comp4.2', 'Comp4.n', ...
%        'Comp5.1.1', 'Comp5.2.1', 'Comp5.n.1', ... 
%        'Comp5.1.2', 'Comp5.2.2', 'Comp5.n.2', ...
%        'Comp6.1', 'Comp6.2', 'Comp6.n', ...
%        'Comp7.1', 'Comp7.2', 'Comp7.n', .../gpfs/projects/bsc21/repsol/data//UNT_ELASTIC__2D_GARVINFLAT/tests/FMD_001/reference/ref-X
%        'Comp8', 'Comp9'
%        }
% 
% nodes={'UCp1', 'BG1', 'Comp1', ... 
%        'UCp2', 'Comp6.1','Comp6.2', 'Comp6.n', ...
%        'Comp6.1','Comp6.2', 'Comp6.n',...
%        'BG2', 'BG3', 'BG4', 'Comp1', ...
%        'Comp2', 'Comp3.1', 'Comp3.2', 'Comp3.n', ...
%        'Comp4.1', 'Comp4.2', 'Comp4.n', ... 
%        'Comp5.1.1', 'Comp5.2.1', 'Comp5.n.1', ... 
%        'Comp5.1.2', 'Comp5.2.2', 'Comp5.n.2', ...
%        'Comp6.1', 'Comp6.2', 'Comp6.n', ... 
%        'Comp6.1', 'Comp6.2', 'Comp6.n', ...
%        'Comp7.1', 'Comp7.2', 'Comp7.n', ...
%        'Comp8', 'Comp8', 'Comp8', ...
%        'Comp9', 'Tend'
%        }

edges={'WORKFLOW START', 'WORKFLOW START', 'WORKFLOW START', ... 
       'Event priority', 'Event priority', 'Event priority', 'Event priority', ...
       'UC Protocol','UC Protocol', 'UC Protocol', ...
       'Event listener', 'Event updater', 'Event evaluator', 'Abort', 'Restart'...
       'Unify sources', 'CMT', 'CMT', 'CMT', ...
       'Slip generator 1', 'Slip generator  2', 'Slip generator n', ...
       'Data location 1', 'Data location 2', 'Data location n', ...
       'Data location 1', 'Data location 2', 'Data location n', ...
       'Model builder 1', 'Model builder 2', 'Model builder n', ... 
       'Params builder 1', 'Params builder 2', 'Params builder n', ...
       'HPC Simulation 1', 'HPC Simulation 2', 'HPC Simulation n', ...
       'HPC Postprocess 1', 'HPC Postprocess 2', 'HPC Postprocess n', ...
       'Results unifier', 'Analisys and decision making'
       }

nodes={'Event priority', 'Event listener', 'Unify sources', ... 
       'UC Protocol', 'HPC Simulation 1', 'HPC Simulation 2', 'HPC Simulation n', ...
       'HPC Simulation 1', 'HPC Simulation 2', 'HPC Simulation n',...
       'Event updater', 'Event evaluator', 'Abort', 'Restart', 'Unify sources', ...
       'CMT',  'Slip generator 1', 'Slip generator  2', 'Slip generator n', ...
       'Data location 1', 'Data location 2', 'Data location n', ... 
       'Model builder 1', 'Model builder 2', 'Model builder n', ... 
       'Params builder 1', 'Params builder 2', 'Params builder n', ...
       'HPC Simulation 1', 'HPC Simulation 2', 'HPC Simulation n', ... 
       'HPC Simulation 1', 'HPC Simulation 2', 'HPC Simulation n', ...
       'HPC Postprocess 1', 'HPC Postprocess 2', 'HPC Postprocess n', ...
       'Results unifier', 'Results unifier', 'Results unifier', ...
       'Analisys and decision making', 'WORKFLOW END'
       }


G = digraph(edges,nodes)

figure('units','normalized','outerposition',[0 0 1 1])
p = plot(G)
%p.Marker = 's';
p.NodeColor = 'r';
p.MarkerSize = 15

