# syntax=docker/dockerfile:experimental
FROM registry.gitlab.com/cheese-coe/ucis4eq/base:latest

# Install dependencies
RUN pip install --upgrade setuptools; pip install numpy flask pymongo pyyaml requests; pip install obspy webdavclient3

ARG CACHEBUST=1    

# Pass the SSH key (both public and private)
ARG SSH_PUB
ARG SSH_PRV

RUN mkdir -m 700 /root/.ssh; \
  touch /root/.ssh/known_hosts; \
  ssh-keyscan dt01.bsc.es > /root/.ssh/known_hosts; \
  ssh-keyscan mn1.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan mn2.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan mn3.bsc.es >> /root/.ssh/known_hosts  
  
# Add the keys and set permissions
RUN echo "$SSH_PRV" > /root/.ssh/id_rsa && \
echo "$SSH_PUB" > /root/.ssh/id_rsa.pub && \
chmod 600 /root/.ssh/id_rsa && \
chmod 600 /root/.ssh/id_rsa.pub

# Prepare the service to run
RUN mkdir -p /opt/services;
    
# Expose the Flask application port
EXPOSE 5003

# Obtain the SalvusService App
RUN curl --request GET --header 'PRIVATE-TOKEN: glpat-8SmAHs1yjVmWq6-q_bkz' 'https://gitlab.com/api/v4/projects/12232768/repository/files/code%2Fservices%2FsalvusService.py/raw?ref=master' > /opt/services/salvusService.py

# Prepare an script able to start the slip-generator service
RUN echo "python /opt/services/salvusService.py" >> /opt/services/start.sh
 
# Start a shell
ENTRYPOINT ["/bin/bash", "/root/scripts/launcher.sh"]
