###
###   Docker file for the ucis4eq services
###

version: '3'

services:
  DAL:
    network_mode: "host"
    image: mongo:3.4
   # hostname: mongo
    ports:
      - "27017:27017"
      

# TODO: Add the rest of Dockers here 
  
