# Obtain a clean python capable distribution
FROM python:3.7

# Set the working directory
WORKDIR /workspace

# Install basis packages
RUN apt-get update && apt-get install -y vim

# Install Miniconda3
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh \
    && echo PATH="/root/miniconda3/bin/":$PATH >> /root/.bashrc

# Obtain the Salvus environment
RUN wget \ 
    https://mondaic.com/environment.yml \
    && /root/miniconda3/bin/conda env create -n salvus -f environment.yml \
    && rm -f environment.yml

SHELL ["/bin/bash", "--login", "-c"]
    
RUN /root/miniconda3/bin/conda init bash

# Activate the environment, and make sure it's activated:
RUN echo "conda activate salvus" >> ~/.bashrc

# Install Salvus (except salvus-compute)
ARG SALVUS_USERNAME
ARG SALVUS_PASSWORD

# Copy and decompress the Salvus scripts and launcher into /root directory
ADD salvus.tar.gz Utils

RUN pip install Utils/Salvus/python_packages/salvus-*.whl \
    && cp Utils/Salvus/salvus-licenses.toml /root/.salvus-licenses.toml \
    && cp Utils/salvus-launcher.sh /root/ \
    && rm -fr Utils 
#    && sed -i "s/USERNAME/$SALVUS_USERNAME/g" /root/.salvus-licenses.toml \
#    && sed -i "s/PASSWORD/$SALVUS_PASSWORD/g" /root/.salvus-licenses.toml \
    
# Activating this plug-in results in nicer error traces in the notebooks.
#RUN jupyter nbextension enable skip-traceback/main
 
# Start a shell
ENTRYPOINT ["/bin/bash", "/root/salvus-launcher.sh"]
