# Obtain a clean Ubuntu distribution
FROM registry.gitlab.com/cheese-coe/ucis4eq/base:latest

# Install Python 3.5.6
RUN cd /usr/src; wget -nv --show-progress --progress=bar:force:noscroll https://www.python.org/ftp/python/3.5.6/Python-3.5.6.tgz; tar xzf Python-3.5.6.tgz
RUN cd /usr/src/Python-3.5.6; ./configure --enable-optimizations; make altinstall

# Prepare Python
RUN rm /usr/local/bin/python; ln -s /usr/local/bin/python3.5 /usr/local/bin/python
RUN rm /usr/local/bin/pip; ln -s /usr/local/bin/pip3.5 /usr/local/bin/pip

# Install dependencies
RUN pip install webdavclient3 numpy flask pymongo pyyaml; pip install requests obspy #ucis4eq

# Obtain the EQ events listener service
RUN curl --request GET --header 'PRIVATE-TOKEN: bZA9JyDsdqyzawJngzzy' 'https://gitlab.com/api/v4/projects/12232768/repository/files/code%2Fservices%2Flistener.py/raw?ref=master' > /root/services/listener.py

# Prepare an script able to start MongoDB and run the events listener service
RUN echo "python /root/services/listener.py config_events" >> /root/services/start.sh

# Entry point
ENTRYPOINT ["sh", "/root/services/start.sh"]
