###############################################################################
########################### CREDENTIALS STAGES  ###############################
###############################################################################
ARG IMAGE
FROM ${IMAGE}

# Pass the Private SSH key
ARG SSH_PRV

RUN mkdir -m 700 /root/.ssh; \
  touch /root/.ssh/known_hosts; \
  ssh-keyscan dt01.bsc.es > /root/.ssh/known_hosts; \
  ssh-keyscan mn1.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan mn2.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan mn3.bsc.es >> /root/.ssh/known_hosts; \
  ssh-keyscan ela.cscs.ch >> /root/.ssh/known_hosts
  
# Add the keys and set permissions
RUN echo "$SSH_PRV" > /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa 

# Entry point
ENTRYPOINT ["sh", "/root/services/start.sh"]
