###############################################################################
###########################    BUILD STAGE     ################################
###############################################################################

# syntax=docker/dockerfile:experimental
FROM registry.gitlab.com/cheese-coe/ucis4eq/base:latest AS build

# Install dependencies
RUN pip install --upgrade setuptools; pip install numpy flask pymongo pyyaml requests; pip install obspy webdavclient3

# Prepare the service to run
RUN mkdir -p /opt/services;
    
# Expose the Flask application port
EXPOSE 5003

# Obtain the SalvusService App
RUN curl --request GET --header 'PRIVATE-TOKEN: glpat-8SmAHs1yjVmWq6-q_bkz' 'https://gitlab.com/api/v4/projects/12232768/repository/files/code%2Fservices%2FsalvusService.py/raw?ref=master' > /opt/services/salvusService.py

# Prepare an script able to start the slip-generator service
RUN echo "python /opt/services/salvusService.py" >> /opt/services/start.sh
 
# Start a shell
ENTRYPOINT ["/bin/bash", "/root/scripts/launcher.sh"]
