# Obtain a clean python capable distribution
FROM python:2.7

# Set the working directory
WORKDIR /workspace

# Clone the BBP project 
#RUN git clone https://github.com/SCECcode/bbp.git bbp-19.4.0

# Install BBP
#RUN cd bbp-19.4.0/setup; ./easy_install_bbp_19.4.0.sh

# Install FFTW3
RUN apt-get update && apt-get install -y fftw3 libfftw3-dev gfortran

# Install Python dependencies
RUN pip install numpy matplotlib;

# Install some packages
RUN apt-get -qq update && apt-get -qq install -y python3-pip wget vim > /dev/null

# Install UCIS4EQ
RUN pip3 install --upgrade setuptools; pip3 install numpy flask pymongo requests; pip3 install obspy webdavclient3; pip3 install ucis4eq 

# Copy and decompress the slip generator code into /root directory
ADD deployment/dockers/thirdparties/gp-slip-gen.tar.gz /root/

# Prepare the service to run
RUN mkdir /root/services;

# Expose the Flask application port
EXPOSE 5002

# Obtain the slipGenService App
RUN curl --request GET --header 'PRIVATE-TOKEN: bZA9JyDsdqyzawJngzzy' 'https://gitlab.com/api/v4/projects/12232768/repository/files/code%2Fservices%2FslipGenService.py/raw?ref=master' > /root/services/slipGenService.py

# Prepare an script able to start the slip-generator service
RUN echo "python3 /root/services/slipGenService.py" >> /root/services/start.sh

# Start a shell
ENTRYPOINT ["/bin/bash", "/root/scripts/launcher.sh"]
